### ISSUE TITLE
勉強会1回につき練習問題を1つ作成し、対応するテストとテストコマンドを用意する

### ISSUE THREAD

**Issue by kurupeku** [kurupeku/hello-golang#1]
## 前半の `A Tour of Go` 分配内容

- [x] #11
- [x] #2
- [x] #3
- [x] #4
- [x] #5
- [x] #6
- [x] #7
- [x] #8
- [x] #9
- [x] #10

## 決めたい内容

- 1 ~ 9 までの各回で、その日に学んだ内容を活かせる練習問題を考える
- それぞれを実現するロジックを書くためのメソッドを虫食い状態で用意する
- ↑ のメソッドに対するテストを記述しておき、リモートへプッシュ後にCIが通るかどうかを実践してもらう

**Comment by kurupeku** [comment]
@kudagonbe 

上記を満たすネタを集める
↓
各回1つに絞る
↓
コードに落とし込む

の流れで実施しましょう！
以下に雑多に書き込んでください 🙇

**Comment by kudagonbe** [comment]
第1回の候補：運賃の計算
```
・初乗り運賃 100 円
・1 区間ごとに 10 円ずつ加算
・引数に区間Nを数値で受け取り、運賃を返却する関数
・1 ≦ N ≦ 30という条件を満たす（この範囲外の考慮不要）
```
→四則演算（足し算と掛け算のみ）ができればOKなので、取り扱う型をintだけにすれば第1回の範囲内で十分対応できそう

別案：山手線の特定の駅からの運賃計算
[この表](https://www3.cuc.ac.jp/~nagaoka/2017/shori/09/Tokyo_loop_line_fare/index.html)を元にする
```
・山手線の入場駅、出場駅(string)を受け取って、内回り・外回りの運賃を返却する関数を他packageでこちらで事前準備
・新宿駅からの運賃、上野駅からの運賃を計算する関数をそれぞれ実装する
・実装する関数の引数には、出場駅のみを渡す
・内回り、外回りの運賃をそれぞれ返却する
・山手線に存在しない駅名は入力されない前提（駅名のバリデーションやエラー処理等は不要）
・入場と出場が同じ駅の場合は0, 0を返却
```
→他packageの関数呼び出しや、多値返却の制御に慣れてもらう。取り扱う型はstringとintのみなので十分対応できそう
→応用編として、内回りと外回りの営業キロを返却する関数から運賃を割り出す問題も作れそう（ただしif文とかが必要）

**Comment by kurupeku** [comment]
@kudagonbe 
自分も探してみようと開いたらめっちゃいい問題頂いてますね（特に後半）

> ・新宿駅からの運賃、上野駅からの運賃を計算する関数をそれぞれ実装する

運賃までやっちゃうと難易度が低すぎる気がするので距離だけ返すとかどうでしょう？

> ・実装する関数の引数には、出場駅のみを渡す

内回り用関数と外回り用関数の２つに分けて用意するのはどうでしょう？？

**Comment by kurupeku** [comment]
## 第１回候補

### タクシー料金計算

> 初乗り料金が1700mまで610円、それ以降は313mごとに80円のタクシーがある。このタクシーに乗った距離をm単位で入力し、料金を計算するプログラムを作成せよ。
> [出典](http://www.cc.kyoto-su.ac.jp/~mmina/bp1/hundredKnocksMiddle.html)

こちらを少し拡張して、

- 入力値を `10.5km` `1250m` など単位付きの距離を入力値にする
- 単位付き距離 -> メートルのみの数値にパースする関数を外部パッケージに用意する
- 標準料金と深夜料金（とエラー）を戻り値として返却する

とかシンプルで良さそうだと思いました

**Comment by kurupeku** [comment]
思ったよりコメント量が多くなりそうなのでIssueを回ごとに分割します！
