### ISSUE TITLE
Errorsまで+卒業試験

### ISSUE THREAD

**Issue by kurupeku** [kurupeku/hello-golang#10]

**Comment by kurupeku** [comment]
お…思いつかん…

**Comment by kudagonbe** [comment]
型Switchを使った例題を考えたいのですが、いい感じのテーマ考え中です・・

**Comment by kudagonbe** [comment]
## ハンバーガーショップの料金計算

・ハンバーガーやポテトの単品料金やセット料金を計算する
・準備する型は`HamburgerSet`,`Hamburger`,`FrenchFries`,`Topping`の4種
・上記の型のいずれかの変数をinterface{}で渡して、料金を計算するcalc関数を準備
・セットの料金は単品料金合計の30%引き
・関数内では型Switchを書いて、どの種類の商品が来ても料金を返却できるようにする
・ハンバーガーはトッピングのスライスを保持
・ハンバーガーの料金はトッピングの合計金額で決まる
・フライドポテトはサイズを保持
・フライドポテトの料金はサイズで決まる
・セットの料金はハンバーガー+フライドポテトの料金の30%引き
・それぞれの型で料金を計算するメソッドを持たせるのは禁止

単純な型Switchだけだと簡単すぎるので、再帰の要素も入れられないか検討した結果です

**Comment by kurupeku** [comment]
おお…いい！

> それぞれの型で料金を計算するメソッドを持たせるのは禁止

これあえて明記せず、算出用メソッドを持った interface にアサーションして処理とかむしろやってほしい気がするのですがいかがでしょう？

複数クリア方法がある方が卒検っぽくないですか？

**Comment by kurupeku** [comment]
> 再帰の要素も入れられないか検討した結果です

僕の読解力だとどこが再帰になるかわかりませんでした。。。
トッピングのとこですか？？

**Comment by kudagonbe** [comment]
@kurupeku 

> どこが再帰になるかわかりませんでした。。。

コード書いてイメージ伝えたいのですが今スマホなのでハードル高い。。！！

そしてちょっと考え直しましたが、再帰の強制はだいぶ難しいので、むしろ実装の自由度を持たせた方が良いかもです。
型Switchにも固執せずに、empty interfaceを受け取る料金計算関数と各種構造体だけを準備するのが良さそうに思いました。

**Comment by kudagonbe** [comment]
・山手線にICカードor切符で乗る
・出発駅、到着駅を渡して、外回りor内回りの安い方を計算
・ICカードと切符で料金変える（ICカードの方が安い）
・ICカードの場合は残高+ポイント、切符の場合は切符料金と運賃を比較。足りなければfalse

**Comment by kurupeku** [comment]
`subject-examples` に取り込んだのでクローズ
