### ISSUE TITLE
導入（環境構築、GitHub準備）

### ISSUE THREAD

**Issue by kurupeku** [kurupeku/hello-golang#11]
## 当勉強会（基礎編）のガイダンス

- 目的・目指すゴール
  - 非アプリケーションエンジニアでなくとも Go の基礎文法を扱えるようになること
    - ITリテラシーはあるがプログラミング言語を日常的に触らない人までが対象
    - 基礎的な 変数、配列、条件分岐 などの概念は理解しているものとする
- 各会の進め方
  - 前半
    - まずは各回に割り振った A Tour of Go のトピックをファシリテーターが説明していく
    - プログラムの記述がある部分は都度手元で実行してもらう
    - トピックごとにわからないところがないかを確認し、都度質問してもらう
  - 後半
    - 当リポジトリにある回ごとの実践問題をクリアしてもらう
    - ローカルに Pull した上で自分用のブランチを切り、そちらの該当メソッド部分を実装
    - 実装が終わったと思ったらリモートにPushし、CI が通ればクリア
- 当リポジトリの運用方法
  - ブランチの命名規則
    - `講座開始月/自身の名前`
      - 今後使い回す可能性を考えて
  - [x] #14
    - Git の取り扱いは特別説明を行わない 
- 演習時の注意点・方針
  - 早くクリアした人は他の人のヘルプをする
  - [x] #13
    - 事前着手は行わないように周知

## 環境構築

- Golang の実行環境構築
  - Docker 派と ローカルインストール派をサポート
    - それぞれの手順を資料化し、進捗確認しながら進める
    - コンテナで行う場合も基本的にはローカルにインストールを推奨（エディタなどの補完に使用するため）
    - `Docker 上で開発する` という概念を説明する
- タスクランナーの導入
  - 導入手順を案内
  - Makefile は Windows と相性が良くないので別途用意
    - [x] #12
- テストの実行方法
  - Docker 派と ローカルインストール派をサポート
  - タスクランナーに事前定義しておいたものを利用する手順も紹介
  - `chapter 0` に用意したテストが実行できる状態になれば導入完了

## やること

- [x] #15

**Comment by kurupeku** [comment]
この内容を説明するためのスライド的なものを作るか、いっそのこと GithubPages に公開したい

**Comment by kudagonbe** [comment]
まとめありがとうございます！
GitHubPagesでの公開、自分も賛成です。その他各issueについてもコメントします！

**Comment by kurupeku** [comment]
Pages の構成やデプロイ方法などはまた会社で相談させてください 🙇

**Comment by kudagonbe** [comment]
@kurupeku 

>コンテナで行う場合も基本的にはローカルにインストールを推奨（エディタなどの補完に使用するため）

devcontainerを使う場合もこれは同様なのでしたっけ？？

**Comment by kurupeku** [comment]
VSCodeかつdevcontainerを起動させて書く人は不要ですね！
ただ導入方法自体は知っておくべきかと思ったのでそう書きました！

**Comment by kurupeku** [comment]
関連タスクすべて完了なのでクローズします

**Comment by chmikata** [comment]
![LGTM](https://image.lgtmoon.dev/183656)
