### ISSUE TITLE
予習で実装を行うのを許可するか

### ISSUE THREAD

**Issue by kurupeku** [kurupeku/hello-golang#13]
どっちにしましょう？

**Comment by kurupeku** [comment]
全員事前にクリアしてしまっているとやることがなくなってしまうので、当日までは未着手でお願いするのがベターと考えます

**Comment by kudagonbe** [comment]
@kurupeku 
>全員事前にクリアしてしまっているとやることがなくなってしまうので、当日までは未着手でお願いするのがベターと考えます

演習の内容は公開するので着手はできてしまうのですが、
当日暇になってしまうかもなので、表向きはこのようにアナウンスしておくのが良いですね！

**Comment by kurupeku** [comment]
かしこまりました！
着手はしないようにというアナウンスを0回で行う方向にします！
