### ISSUE TITLE
Git の扱いがわからない場合の補足を入れるか

### ISSUE THREAD

**Issue by kurupeku** [kurupeku/hello-golang#14]
さすがにいらない気がするのですが、どうでしょうか？

**Comment by kudagonbe** [comment]
cloneしてブランチ切ってpushするだけですよねぇ。。
当日詰まる人がいるかもしれませんが、その場合は個別フォローで良いのではないかと
少なくとも、我々としてGitの説明をするための事前準備は不要と思います！

**Comment by kurupeku** [comment]
かしこまりました！
では基本触れない方向で行きましょう！
