### ISSUE TITLE
第0回用の資料作成

### ISSUE THREAD

**Issue by kurupeku** [kurupeku/hello-golang#15]
- https://github.com/kurupeku/hello-golang/issues/11

の内容を伝えるための資料作成が必要

- [ ] 提供方法を決定
  - `chapter 0` のディレクトリを作ってその配下に `md` 形式で用意
  - `public` ディレクトリを用意し、その中に静的ファイルとして用意し GitHub Pages で公開
  - Slide で作成
- [ ] 資料作成

**Comment by kurupeku** [comment]
導入方法と目的は複数回開催するとしても公開しておきたい ＆ 見栄えがいいので Pages で公開を個人的には希望します！！

**Comment by kurupeku** [comment]
marpならこれを使うと上手くできそう

- https://hub.docker.com/r/marpteam/marp-cli/

**Comment by kudagonbe** [comment]
別のリポジトリでpages作ったときは[こんな感じ](https://kudagonbe.github.io/jpcal/)でREADMEのマークダウンから自動生成とかもできましたね。
ベストなやり方は分からないのですが、大変でなければPagesで公開に一票です！
（Slideは大変そう・・）

**Comment by kurupeku** [comment]
僕のイメージ的には説明資料とREADMEでかぶる部分が多いので、見やすさに降ってみるほうが良いかも？
という理由でSlideを候補にしました！

Marp 自体は非常に簡単に書けるので、静的ファイル化する処理をタスク化できればただの Pages 公開と変わらないのでそのへん調査しておきます！

**Comment by kurupeku** [comment]
marp用のマークダウン作成後に

```bash
task marp -- <ファイル名>
```

して頂ければホスティング用の静的htmlファイルとして出力されます 🙏
