### ISSUE TITLE
Short Variablesまで

### ISSUE THREAD

**Issue by kurupeku** [kurupeku/hello-golang#2]

**Comment by kurupeku** [comment]
*今本さん案*

第1回の候補：運賃の計算
```
・初乗り運賃 100 円
・1 区間ごとに 10 円ずつ加算
・引数に区間Nを数値で受け取り、運賃を返却する関数
・1 ≦ N ≦ 30という条件を満たす（この範囲外の考慮不要）
```
→四則演算（足し算と掛け算のみ）ができればOKなので、取り扱う型をintだけにすれば第1回の範囲内で十分対応できそう

別案：山手線の特定の駅からの運賃計算
[この表](https://www3.cuc.ac.jp/~nagaoka/2017/shori/09/Tokyo_loop_line_fare/index.html)を元にする
```
・山手線の入場駅、出場駅(string)を受け取って、内回り・外回りの運賃を返却する関数を他packageでこちらで事前準備
・新宿駅からの運賃、上野駅からの運賃を計算する関数をそれぞれ実装する
・実装する関数の引数には、出場駅のみを渡す
・内回り、外回りの運賃をそれぞれ返却する
・山手線に存在しない駅名は入力されない前提（駅名のバリデーションやエラー処理等は不要）
・入場と出場が同じ駅の場合は0, 0を返却
```
→他packageの関数呼び出しや、多値返却の制御に慣れてもらう。取り扱う型はstringとintのみなので十分対応できそう
→応用編として、内回りと外回りの営業キロを返却する関数から運賃を割り出す問題も作れそう（ただしif文とかが必要）

**Comment by kurupeku** [comment]
@kudagonbe 
自分も探してみようと開いたらめっちゃいい問題頂いてますね（特に後半）

> ・新宿駅からの運賃、上野駅からの運賃を計算する関数をそれぞれ実装する

運賃までやっちゃうと難易度が低すぎる気がするので距離だけ返すとかどうでしょう？

> ・実装する関数の引数には、出場駅のみを渡す

内回り用関数と外回り用関数の２つに分けて用意するのはどうでしょう？？

**Comment by kurupeku** [comment]
## 第１回候補

### タクシー料金計算

> 初乗り料金が1700mまで610円、それ以降は313mごとに80円のタクシーがある。このタクシーに乗った距離をm単位で入力し、料金を計算するプログラムを作成せよ。
> [出典](http://www.cc.kyoto-su.ac.jp/~mmina/bp1/hundredKnocksMiddle.html)

こちらを少し拡張して、

- 入力値を `10.5km` `1250m` など単位付きの距離を文字列として入力値に受け取る
- 単位付き距離 -> メートルのみの数値にパースする関数を外部パッケージに用意する
- 標準料金と深夜料金（とエラー）を戻り値として返却する

とかシンプルで良さそうだと思いました

**Comment by kudagonbe** [comment]
>タクシー料金計算

これはめちゃ良さそうですね！
外部パッケージの関数呼び出し、単純な計算、多値返却の知識だけで出せるので良いと思います！
`error`については学習前ですが、外部パッケージの関数を呼び出した時に返却された`error`をそのまま返すだけであればできそうですね。

私の出した案は、営業キロから運賃を出すのに条件分岐が必要なので、if文の回（#4）でもよいかもと思いました！

**Comment by kudagonbe** [comment]
そういえば、Tour of Goは四則演算の書き方は出てこないですね。。
ハマりポイントもあまりないとは思いますが、この回の演習問題をやる前に少しだけ説明したほうが良いかもと思いました

**Comment by kurupeku** [comment]
> そういえば、Tour of Goは四則演算の書き方は出てこないですね。。
> ハマりポイントもあまりないとは思いますが、この回の演習問題をやる前に少しだけ説明したほうが良いかもと思いました

え？と思って確認したらホンマですね。。。
流石に別途時間をガッツリ取るみたいな必要はなさそうだと思いますが、一通り説明はしたほうが良さそうですね！

**Comment by kurupeku** [comment]
> `error` については学習前ですが、外部パッケージの関数を呼び出した時に返却された `error` をそのまま返すだけであればできそうですね。

ぶっちゃけなくしてもいいんですけど、距離の値に異常値が来たときを考えるとあったほうが…みたいに思った次第です。
異常値はこない！という前提にしてしまうのであればいっそ端折る方がいいかもですね！

**Comment by kudagonbe** [comment]
この回はタクシー料金で良さそうですね！
エラー返却は、一応入れましょうか！
確か`strconv.Atoi`がerrorを返す可能性あったと思うので、そこでエラーが帰ってきたらそのまま返却してもらうとか

**Comment by kudagonbe** [comment]
## 確定：タクシー料金計算
https://github.com/kurupeku/hello-golang/issues/2#issuecomment-1264562872
・`strconv.Atoi`のerrorはutilで握りつぶしてpanic発生させる
