### ISSUE TITLE
Numeric Constantsまで

### ISSUE THREAD

**Issue by kurupeku** [kurupeku/hello-golang#3]

**Comment by kurupeku** [comment]
## 小銭計算

> 指定した金額を100円玉と10円玉と1円玉だけで、できるだけ少ない枚数で支払いたい。金額を入力するとそれぞれの枚数を計算して表示するプログラムを作成せよ。
> [出典](http://www.cc.kyoto-su.ac.jp/~mmina/bp1/hundredKnocksMiddle.html)

こちらを拡張して

- 事前に定数で6種類の額の硬貨（1, 5, 10, 50, 100, 500）を `Numeric Constants` として定義しておく
- 第一引数に `int` で任意の金額を受け取る
- 消費税（10%）を追加して *0.1の桁を四捨五入*（単純に `int` にすると切り捨てになる） して税込みを算出
- 各硬貨のみを使用して最も少ない枚数で支払える組み合わせを返す
- 戻り値は `500円玉の枚数, 100 〃, 50 〃, 10 〃, 5 〃, 1 〃` にしてもらう

とかどうでしょ？
消費税の計算で強制的に `float` を使用するので型変換も実践できるのではという狙いです！

**Comment by kudagonbe** [comment]
@kurupeku 
めちゃめちゃいいですね！！
この回の範囲がだいぶピンポイントだったので全然良いお題が見つけられなかったのですが、これは完ぺきでは・・！

**Comment by kudagonbe** [comment]
## 確定：小銭計算
https://github.com/kurupeku/hello-golang/issues/3#issuecomment-1264571941
