### ISSUE TITLE
全ての演習問題のREADMEにテスト実行方法を載せる

### ISSUE THREAD

**Issue by h-imamoto** [kurupeku/hello-golang#36]
@kurupeku 
演習問題ごとに、go-taskでテストを実行するコマンドを載せておいた方が優しいかもと思ったので、
載せちゃっても良いでしょうか？？

**Comment by kurupeku** [comment]
@h-imamoto 
ありがたいです！
各READMEがいいですかね？

**Comment by h-imamoto** [comment]
@kurupeku 
了解です！では仰せつかりたいと思います！

>各READMEがいいですかね？
その想定でした！
