### ISSUE TITLE
Stacking defersまで

### ISSUE THREAD

**Issue by kurupeku** [kurupeku/hello-golang#4]

**Comment by kudagonbe** [comment]
#2 に書いたものの改善版です。

山手線の特定の駅からの運賃計算
[この表](https://www3.cuc.ac.jp/~nagaoka/2017/shori/09/Tokyo_loop_line_fare/index.html)を元にする
```
・山手線の入場駅、出場駅(string)を受け取って、内回り・外回りの営業キロを返却する関数を他packageでこちらで事前準備
・新宿駅からの運賃、上野駅からの運賃を計算する関数を内回りと外回りでそれぞれ実装する
・実装する関数の引数には、出場駅のみを渡す
・山手線に存在しない駅名は入力されない前提（駅名のバリデーションやエラー処理等は不要）
・入場と出場が同じ駅の場合は0を返却
```
→内回りは`if`, 外回りは`Switch with no condition`を参考にして運賃計算の条件分岐を書くという縛りにすると、
　ifとswitchの書き方がそれぞれ身につくような気がしています。

**Comment by kurupeku** [comment]
こっちだと実装をそこそこ回答者に移乗できるのでいいと思います！

可能ならなんとか `defer` も突っ込みたいところですが…ちょっと思いつかないので↑のまま実装しても良いかと思います！

**Comment by kurupeku** [comment]
これ、そのままだと `for` の要素がないような気がするので、現在の駅名を入れたら次の駅名とそこまでの距離を返す関数を用意するくらいにして、それをループさせて目的の駅が来たら `break` する感じにするのはどうでしょう？？

**Comment by kudagonbe** [comment]
@kurupeku 
その案、めちゃめちゃ良いと思います！！

**Comment by kurupeku** [comment]
@kudagonbe 
出発駅を東京駅のみにしようと思います！

- 後ほど出てくる卒検とヘルパーを共用したいので変則的なものを作りづらい
  - スライスの特定の位置からスタートする場合、インデックスの取得や操作を結構必要としてしまう
- 出発駅が変わっても実装はほぼ変わらないため、ほぼ同じコードを複数書く必要がでてくる

**Comment by kudagonbe** [comment]
> @kudagonbe 
> 出発駅を東京駅のみにしようと思います！
> 
> - 後ほど出てくる卒検とヘルパーを共用したいので変則的なものを作りづらい
>   - スライスの特定の位置からスタートする場合、インデックスの取得や操作を結構必要としてしまう
> - 出発駅が変わっても実装はほぼ変わらないため、ほぼ同じコードを複数書く必要がでてくる

@kurupeku 
承知です！
確かに出発駅を可変にすると一手間増えるので、その方針で良いと思いました！
