### ISSUE TITLE
Struct Literalsまで

### ISSUE THREAD

**Issue by kurupeku** [kurupeku/hello-golang#5]

**Comment by kudagonbe** [comment]
演習問題案：ポイント機能付き交通系ICカード
```
・フィールドにチャージ残高（int）、ポイント（int）を持つstructのCard型を使う
・Cardと運賃（int）を渡してICカードを使うuse関数を実装
・use関数を呼び出す際は以下の処理を実行する
　・運賃>=ポイント残高の場合はポイント残高を減らす
　・運賃<ポイント残高の場合はチャージ残高を減らす
　・チャージ残高が足りない場合は3000円オートチャージ（＝チャージ残高を増やす）
　・チャージ残高から運賃を支払う場合は、運賃の10%のポイント付与（＝ポイント残高を増やす）
```

この回の範囲でいい感じの問題設定が思い浮かばなかったです。。。
use関数の引数をポインタ型にするか値型にするかの違いを理解してもらいたいのですが、一から関数を書いてもらうと事前にテストを準備しておけないのが悩ましいです

**Comment by kurupeku** [comment]
僕も探してみましたけどあまりいい感じのが見当たりませんでした。。。

`use関数` というより `改札関数`  みたいな名前にするとイメージしやすいかなぁという点と、返り値を `bool` 型にして `運賃 > 残高 + ポイント` なら `false` 、それ以外なら `true` を返す関数にするというのはどうでしょう？

かつ、 引数に渡す `Card` 構造体をポインタ型にして、 `false` の場合は渡された構造体をそのまま返す、 `true` の場合は ポイント -> 残高 の順で減算するみたいにするとポインタで構造体をいじるの意味にフォーカスされてわかりやすいのでは？と思いました。

**Comment by kudagonbe** [comment]
@kurupeku 
それは分かりやすいですね
自分も、構造体のポインタ型をいじる部分にフォーカスを当てたかったので、その部分が明確になるという意味でも良いと思いました
この回はこのお題で進めましょうか！
