### ISSUE TITLE
Range continuedまで

### ISSUE THREAD

**Issue by kurupeku** [kurupeku/hello-golang#6]

**Comment by kurupeku** [comment]
## 真ん中を落とす達磨落としゲーム

`Slice` を渡すとちょうど真ん中の要素だけをふっ飛ばした Slice を返す関数を実装する

- 長さが奇数の場合は中央を、偶数の場合は中央値2つのうち小さい方をふっとばす
- 渡す `Slice` はなんでもいいがとりあえず `string` とか
- 長さが1つ以下の場合はそのまま返す

これだと無難に長さを使った操作をする必要性と新たなスライスに詰め直して返す必要性があってちょうどよいのではと思いました

**Comment by kurupeku** [comment]
## マトリクス掛け算

`Slice` を渡すとその要素同士を掛け合わせたマトリクス状態のスライスを返す関数を作る

e.g.
`[]int{1, 2, 3}` => `[][]int{{1, 2, 3}, {2, 4, 6}, {3, 6, 9}}`

単純ですがリテラル表記のややこしさと二次元配列特有のややこしさで結構難しいのでは？と思い挙げました。
Slice になれるには意外と良いのではというアプローチの課題です

**Comment by kudagonbe** [comment]
お題ありがとうございます！
マトリクス掛け算はrangeも出す要素ありますし、おそらく人によっては結構難しいので難易度はちょうど良さそうに思いました！
達磨落としは書き方が分かれば瞬殺かもしれないので、「両端を除く値が一番小さい数」を吹っ飛ばすとかでも良いのかもと思います！

**Comment by kurupeku** [comment]
どっちもわかれば瞬殺系なので両方出すのもありかもです😎
その場合はダルマ落としはそのままで！

**Comment by kurupeku** [comment]
> 達磨落としは書き方が分かれば瞬殺かもしれないので、「両端を除く値が一番小さい数」を吹っ飛ばすとかでも良いのかもと思います！

これいいですね！
これだと単品でもちょうどよいくらいかもしれませんね！

**Comment by kudagonbe** [comment]
結論：2個
