### ISSUE TITLE
The empty interfaceまで

### ISSUE THREAD

**Issue by kurupeku** [kurupeku/hello-golang#9]

**Comment by kudagonbe** [comment]
## カーシェアサービスの料金

・車種によって「ベーシック」「ミドル」「プレミアム」の3段階があり、
　車種の種別と利用時間から利用料金を算出する
・それぞれ料金は以下のとおり
||ベーシック|ミドル|プレミアム|
|:---:|:---:|:---:|:---:|
|15分ごとの料金|220円/15分|330円/15分|440円/15分|
|最大料金(6時間まで)|4,290円|6,490円|8,690円|

実装イメージ
```go
type Car interface {
    PricePer15Minutes() int
    MaxPrice() int
}

// それぞれでCar interfaceを実装
type Basic struct{}
type Middle struct{}
type Premium struct{}

func Calc(car Car, minutes int) (int, error) {
    // 実装
}
```

**Comment by kurupeku** [comment]
# 面積計算

- 三角形・四角形・円の3種類の型を定義
- `Area` 構造体のメソッドに `[]Calculator` として渡して、合計面積を算出する関数を実装
- 各図形側で `Area()` を実装させて異なる計算方法から合計面積のみを抽象化して抜き出す構造にする

**Comment by kurupeku** [comment]
考えているうちにめっちゃいいのを投稿頂いていた…

**Comment by kudagonbe** [comment]
確定：カーシェア
